version: "3.9"

services:
  app:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: password

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: shopdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
